micronaut:
  application:
    name: gorm-shared-domains-micornaut

dataSource:
  pooled: true
  dbCreate: create-drop
  url: jdbc:h2:mem:devDb
  driverClassName: org.h2.Driver
  username: sa
  password:
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
